DROP TABLE IF EXISTS services;
CREATE TABLE services (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 title TEXT NOT NULL,
 txt TEXT NOT NULL
);

DROP TABLE IF EXISTS users;
CREATE TABLE users (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 fio TEXT NOT NULL,
 login TEXT NOT NULL,
 password TEXT NOT NULL,
 email TEXT NOT NULL,
 phone TEXT NOT NULL,
);

CREATE TABLE zayavki (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 fio TEXT NOT NULL,
 email TEXT NOT NULL,
 phone TEXT NOT NULL,
 service TEXT NOT NULL,
 message TEXT NOT NULL,
 )
 CREATE TABLE zap (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 fio TEXT NOT NULL,
 datetime TEXT NOT NULL
 )

 CREATE TABLE users (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 login TEXT NOT NULL,
 password TEXT NOT NULL
 )
  CREATE TABLE admin (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 login TEXT NOT NULL,
 password TEXT NOT NULL
 )